version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing cfn-lint and taskcat package ....."
      - pip install --upgrade pip
      - pip install cfn-lint
      - pip install taskcat
  pre_build:
    commands:
      - echo "Running cfn-lint to create CloudFormation template ....."
      - cfn-lint main.yml  # Build projects
  build:
    commands:
      - echo "Running Taskcat for validating template"
      - taskcat test run 
  post_build:
    commands:
      - echo "Validation complete"
artifacts:
  files:
    - main.yml