name: Terraform Deployment with Checkov

on:
  push:
    branches:
      - add-checkov
  pull_request:
    branches:
      - add-checkov

jobs:
  terraform:
    name: Deploy Terraform Modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7 

      - name: Terraform Init
        run: terraform -chdir=./NT548.P11_Lab2/Terraform init

      - name: Terraform Validate
        run: terraform -chdir=./NT548.P11_Lab2/Terraform validate

      - name: Terraform Plan
        run: terraform -chdir=./NT548.P11_Lab2/Terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform -chdir=./NT548.P11_Lab2/Terraform apply -auto-approve tfplan

  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov on VPC module
        run: |
          checkov -d ./NT548.P11_Lab2/Terraform/modules/vpc --framework terraform | grep PASSED
          echo "VPC module scanned."
        continue-on-error: true

      - name: Run Checkov on Route Table module
        run: |
          checkov -d ./NT548.P11_Lab2/Terraform/modules/route_table --framework terraform | grep PASSED
          echo "Route Table module scanned."
        continue-on-error: true

      - name: Run Checkov on NAT Gateway module
        run: |
          checkov -d ./NT548.P11_Lab2/Terraform/modules/nat_gateway --framework terraform | grep PASSED
          echo "NAT Gateway module scanned."
        continue-on-error: true

      - name: Run Checkov on Security Group module
        run: |
          checkov -d ./NT548.P11_Lab2/Terraform/modules/security_group --framework terraform | grep PASSED
          echo "Security Group module scanned."
        continue-on-error: true

      - name: Run Checkov on EC2 module | grep PASSED
        run: |
          checkov -d ./NT548.P11_Lab2/Terraform/modules/ec2 --framework terraform
          echo "EC2 module scanned."
        continue-on-error: true

