name: Terraform Destroy (Manual)

on:
  workflow_dispatch: 
  push:
    branches:
      - add-checkov  

jobs:
  terraform_destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.7

      - name: Terraform Init
        run: terraform -chdir=./NT548.P11_Lab2/Terraform init

      - name: Terraform Destroy
        run: terraform -chdir=./NT548.P11_Lab2/Terraform destroy -auto-approve
